### ISSUE TITLE
Max antal objekter i en shapefil

### ISSUE THREAD

**Issue by dkahad** [Septima/spatialsuite-filereader-public#1]
Jeg kan se, at der er sat max antal objekter til 200 i filereader-plugin.
Kan jeg uden videre hæve denne?

**Comment by rastermanden** [comment]
Det kan hæves men browseren kan muligvis ikke håndtere det hvis det er store mængder data

–
Sendt fra Mailbox

**Comment by dkahad** [comment]
Hej Martin. Har I nogen erfaring med hvor højt den kan sættes, eller er det på prøvebasis :-)

**Comment by karstenpihl** [comment]
Jeg lukket dette issue for nu
