### ISSUE TITLE
Filen kan ikke indlæses hos en bestemt bruger

### ISSUE THREAD

**Issue by markusroesgen** [Septima/spatialsuite-filereader-public#2]
ZIP fil kan ikke indlæses hos en bestemt bruger. Vedhæftet ZIP fil fejler hos en bestemt bruger; den kan indlæses uden problemer på min PC.

Desværre må jeg ikke vedhæfte ZIP-filen på Github :/

![zip](https://cloud.githubusercontent.com/assets/11993556/11501200/a6aa4a12-9832-11e5-9eef-540f645dc267.JPG)

**Comment by rastermanden** [comment]
Hmm

det må vi kigge nærme på.

Kan du prøve at rename filen  til filnavn.zip.txt og vedlægge den issue
eller sende som mail til mig ?

## 

_Martin Bjærge Jensen_
Partner, konsulent
+45 91326943

## martin@septima.dk klavs@septima.dk

Septima P/S
Frederiksberggade 28 2.tv.
1459 København K

www.septima.dk

2015-12-01 13:52 GMT+01:00 Markus Rösgen (Sønderborg Kommune) <
notifications@github.com>:

**Comment by markusroesgen** [comment]
Hej Martin

Filen er vedhæftet.

Venlig hilsen

Sønderborg Kommune
Geodata
Staben - Land, By & Kultur

Markus Rösgen
GIS-medarbejder
T 88 72 58 71 M 27 90 58 71
mcrx@sonderborg.dkblocked::mailto:mcrx@sonderborg.dk
www.sonderborgkommune.dkhttp://www.sonderborgkommune.dk

Fra: Martin Bjærge Jensen [mailto:notifications@github.com]
Sendt: 1. december 2015 14:03
Til: Septima/spatialsuite-filereader-public
Cc: Markus Rösgen
Emne: Re: [spatialsuite-filereader-public] Filen kan ikke indlæses hos en bestemt bruger (#2)

Hmm

det må vi kigge nærme på.

Kan du prøve at rename filen til filnavn.zip.txt og vedlægge den issue
eller sende som mail til mig ?

## 

_Martin Bjærge Jensen_
Partner, konsulent
+45 91326943

## martin@septima.dkmailto:martin@septima.dk <klavs@septima.dk<mailto:klavs@septima.dk>>

Septima P/S
Frederiksberggade 28 2.tv.
1459 København K

www.septima.dkhttp://www.septima.dk

2015-12-01 13:52 GMT+01:00 Markus Rösgen (Sønderborg Kommune) <
notifications@github.commailto:notifications@github.com>:

**Comment by markusroesgen** [comment]
Hej igen

Denne fil virker ikke hos en bestemt bruger (ingen problemer hos mig selv).

Omdøber jeg filen til den første fil jeg har sendt til dig, kan filen også indlæses hos den bestemte bruger.

Venlig hilsen

Sønderborg Kommune
Geodata
Staben - Land, By & Kultur

Markus Rösgen
GIS-medarbejder
T 88 72 58 71 M 27 90 58 71
mcrx@sonderborg.dkblocked::mailto:mcrx@sonderborg.dk
www.sonderborgkommune.dkhttp://www.sonderborgkommune.dk

Fra: Markus Rösgen
Sendt: 1. december 2015 14:23
Til: 'Septima/spatialsuite-filereader-public'
Emne: SV: [spatialsuite-filereader-public] Filen kan ikke indlæses hos en bestemt bruger (#2)

Hej Martin

Filen er vedhæftet.

Venlig hilsen

Sønderborg Kommune
Geodata
Staben - Land, By & Kultur

Markus Rösgen
GIS-medarbejder
T 88 72 58 71 M 27 90 58 71
mcrx@sonderborg.dkblocked::mailto:mcrx@sonderborg.dk
www.sonderborgkommune.dkhttp://www.sonderborgkommune.dk

Fra: Martin Bjærge Jensen [mailto:notifications@github.com]
Sendt: 1. december 2015 14:03
Til: Septima/spatialsuite-filereader-public
Cc: Markus Rösgen
Emne: Re: [spatialsuite-filereader-public] Filen kan ikke indlæses hos en bestemt bruger (#2)

Hmm

det må vi kigge nærme på.

Kan du prøve at rename filen til filnavn.zip.txt og vedlægge den issue
eller sende som mail til mig ?

## 

_Martin Bjærge Jensen_
Partner, konsulent
+45 91326943

## martin@septima.dkmailto:martin@septima.dk <klavs@septima.dk<mailto:klavs@septima.dk>>

Septima P/S
Frederiksberggade 28 2.tv.
1459 København K

www.septima.dkhttp://www.septima.dk

2015-12-01 13:52 GMT+01:00 Markus Rösgen (Sønderborg Kommune) <
notifications@github.commailto:notifications@github.com>:

**Comment by karstenpihl** [comment]
Jeg lukket dette issue for nu
