### ISSUE TITLE
KML filer kan ikke indlæses i v1.0.1 (SpS v4.0.2a)

### ISSUE THREAD

**Issue by markusroesgen** [Septima/spatialsuite-filereader-public#3]
KML filer kan ikke indlæses i v1.0.1 (SpS v4.0.2a). Efter udpegning af kml-filen, bliver hele SPS brugergrænsefladen udgrået men ingen fil bliver indlæst, se skærmdump.

Efterfølgende kan filereader-vinduet ikke lukkes ved at klikke på krydset. SpS reagerer ikke og hele browser vinduet skal refreshes.

Det er testet både i IE11 og Google Chrome.

Ingen problemer med indlæsning af zippede shape-filer.

Hilsen, Markus

**Comment by markusroesgen** [comment]
![Filereader_kml](https://user-images.githubusercontent.com/11993556/57214837-7906d780-6feb-11e9-9784-25189fc62245.JPG)

**Comment by rastermanden** [comment]
Vi undersøger sagen

**Comment by karstenpihl** [comment]
@markusroesgen kan du ikke vedhæfte KML filen (eller sende den på mail), så vi kan teste med den samme fil?

**Comment by markusroesgen** [comment]
[stigruppen_cykelruter_edit-D365FBA4-8681-4F2B-BD20-2FCAB0DA3E4.zip](https://github.com/Septima/spatialsuite-filereader-public/files/3147234/stigruppen_cykelruter_edit-D365FBA4-8681-4F2B-BD20-2FCAB0DA3E4.zip)

**Comment by markusroesgen** [comment]
Jeg indlæser den ikke zippede kml-fil.

**Comment by karstenpihl** [comment]
@rastermanden dette er feljen (i vores miljø):
````
"cmd": "/opt/spatialsuite/sites/default/appbase/spatialmap/WEB-INF/config/modules/thirdparty/septima-test/spatialsuite-filereader/cmd/./getgeojson.sh /opt/spatialsuite/app/mapserver641/ogr2ogr EPSG:25832 /opt/spatialsuite/sites/default/appbase/spatialmap/tmp/ filereader_745215_stigruppen_cykelruter.kml /opt/spatialsuite/app/mapserver641/share/gdal",
"stderr": "ERROR 4: Unable to open EPSG support file gcs.csv.\nTry setting the GDAL_DATA environment variable to point to the\ndirectory containing EPSG csv files.\nFailed to process SRS definition: EPSG:25832\n",
````
Men `/opt/spatialsuite/app/mapserver641/share/gdal` findes ikke (i hvert fald hos os).

**Comment by karstenpihl** [comment]
@markusroesgen kan du prøve en ting for mig?

I filen /WEB-INF/config/modules/thirdparty/septima/filereader/cmd/getgeojson.bat skal du fjerne linjen med:
```
set GDAL_DATA=%5
```
Og prøve at uploade filen igen.

**Comment by karstenpihl** [comment]
Du kan også udkommentere den med
```
REM set GDAL_DATA=%5
```

**Comment by markusroesgen** [comment]
Hej Karsten

Jeg har udkommenteret linjen - desværre uden succes.

Hilsen, Markus

**Comment by karstenpihl** [comment]
Kan jeg logge på serveren eller kan vi prøve over teamview eller lignende?

**Comment by markusroesgen** [comment]
Hej Karsten
Vi kan bruge Teamview. Du er velkommen til at kontakte mig.
Hilsen, Markus

**Comment by karstenpihl** [comment]
Det er løst med version 1.0.3.

Problemet var ikke noget med GDAL_DATA at gøre. Det var blot at det var "25832", der blev sendt med i URL'en i stedet for "EPSG:25832".
