### ISSUE TITLE
Opret brugertema ved at importere data fra fil (”træk og slip filer”) virker ikke når filereader toolet er med i profilen

### ISSUE THREAD

**Issue by markusroesgen** [Septima/spatialsuite-filereader-public#5]
Opret brugertema ved at importere data fra fil ”træk og slip filer” virker ikke efter opgradering til v4.1.0 (testet i IE 11 og Google Chrome v76). Når filereader toolet er udkommenteret i profilen, virker ”træk og slip filer” som beregnet, se vedhæftet beskrivelse.

[Opret brugertema ved at importere data fra fil_træk og slip filer_filereader.pdf](https://github.com/Septima/spatialsuite-filereader-public/files/4339846/Opret.brugertema.ved.at.importere.data.fra.fil_traek.og.slip.filer_filereader.pdf)

**Comment by rastermanden** [comment]
Vi kigger på det

**Comment by klavspc** [comment]
@markusroesgen Det ser ud som om vores drag-n-drop kolliderer med Swecos. Hvordan fungerer det, hvis du udkommenterer vores drag-n-drop og kun lader vores upload forblive i profilen? Fra http://septima.dk/spatialsuite-filereader/:
 ```
//For upload button
 <tool module="filereader" name="filereader-plugin"/>
 //For Drag and Drop
<!-- <tool module="filereader" name="filereader"/> -->
```
Hvilket Sweco-tool skal jeg lægge i profilen for at bruge deres upload?

**Comment by nice-sonderborg** [comment]
Hej Klavs
Jeg har prøvet at deaktivere "Drag and Drop" muligheden for "Filereader" plugin. 
Men sjovt nok det er den der hedder **filereader-plugin**
```
<!--<tool module="filereader" name="filereader-plugin" parenttool="tools-menu"/>-->
<tool module="filereader" name="filereader" displayname="Import af geometri"  parenttool="tools-menu"/>
```
Efter jeg har gjort det. Kan jeg ikke "Drag and Drop" men browse knappen stoppede også med at fungere. kan godt udpege fil, men så sker det intet.

**Comment by nice-sonderborg** [comment]
SWECO's tool hedder userthemes

`<tool ignore="not ModuleDefined('userthemes')" module="userthemes" name="userthemes-addtheme"/>`

**Comment by karstenpihl** [comment]
Tak for det. Vi kigger på det.

**Comment by markusroesgen** [comment]
Hej 
Er der noget nyt? Har I fundet ud af hvorfår filereader kolliderer med Swecos "træk og slip filer" (opret brugertema ved at importere data fra fil)?
Hilsen Markus

**Comment by nice-sonderborg** [comment]
Hej Septima.
Har I mulighed at opdatere værktøjet så den er kompatibel med SpatialSuite v.4 ?

**Comment by karstenpihl** [comment]
Vi skal nok kigget på.

**Comment by nice-sonderborg** [comment]
Hej Karsten
Hvornår kan I fikse i værktøjet?
Der er gået over et år.

**Comment by nice-sonderborg** [comment]
Hej Karsten
Hvornår kan I fikse i værktøjet?
Der er gået over et år.

**Comment by karstenpihl** [comment]
Beklager. Den er smuttet. Jeg ser om vi ikke kan fikse det hurtigst muligt.

**Comment by karstenpihl** [comment]
Så tror jeg det er løst. @nice-sonderborg kan du ikke prøve med version 1.1.0?

https://septima.dk/spatialsuite-filereader/

Da drag and drop konflikter med Spatial Suite, har vi været nødt til at fjerne den funktionalitet. Der er derfor kun muligt at uploade filer via en upload knap som det er lige nu.

**Comment by nice-sonderborg** [comment]
Hej Karsten -  jeg få ingen button på bjælken ved at følge vejledningen her https://septima.dk/spatialsuite-filereader/

**Comment by karstenpihl** [comment]
☠️  Det er det andet tool der skal på. Ikke plugin'et. Jeg har rettet vejledningen.

**Comment by nice-sonderborg** [comment]
Har prøvet i stedet med `<tool module="filereader" name="filereader"/>` så kom knappen frem på bjælken.

Der er den samme fejl ved upload - alt fryser og der sker intet.
Vi bruger SpatialMap version 4.2.2. pt

**Comment by karstenpihl** [comment]
Vi har lige testet på 4.3.0, hvor det virkede med de filer, som følger med modulet i mappen "data". Kan du evt. prøve med en af dem? Ellers send den fil, som du prøver med.

**Comment by nice-sonderborg** [comment]
Det fejler også med dem. 

Vi kan godt afvente til version 4.3.0 - den er også på trapperne.

**Comment by karstenpihl** [comment]
Det burde også virke med 4.2.2. Jeg ser lige om vi ikke kan teste med den version.

**Comment by karstenpihl** [comment]
Men du må alligevel gerne vedhæfte den fil, du tester med.

**Comment by nice-sonderborg** [comment]
[SK.zip](https://github.com/Septima/spatialsuite-filereader-public/files/8342669/SK.zip)

**Comment by nice-sonderborg** [comment]
Jeg har lige testet værktøjet igen og nu loader geometrierne igen. 
Issuet kan lukkes. 
Tak Karsten.
